# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitUploadTest2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitUploadTest2
  pod 'SnapKit'

  target 'GitUploadTest2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitUploadTest2UITests' do
    # Pods for testing
  end

end
